name: Build release bundle

on:
  release:
    types: [published]
jobs:
  bundle-release:
    name: "Bundle with KiCo jar and attach artifacts to release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Read external release tag
        id: config
        run: |
          TAG=$(cat .railsl-release-tag | tr -d '\n')
          echo "TAG=$TAG" >> "$GITHUB_ENV"
      - name: Download artifacts from external release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: kieler
          REPO: railsl
        run: |
          assets=$(gh api repos/$OWNER/$REPO/releases/tags/$TAG --jq '.assets[].url')
          for url in $assets; do
            name=$(gh api $url -H "Accept: application/vnd.github+json" --jq '.name')
            gh api $url -H "Accept: application/octet-stream" > "backend/executor/$name"
          done
        TODO: if the release download is a zip, unzip it first
      
      - name: Create bundle
	  run: |
	    mkdir bundle
	    rsync -a \
	      --exclude bundle \
	      --exclude .git \
	      --exclude .github \
	      --exclude release-bundle.zip \
	      ./ bundle/
	    cd bundle
	    zip -r ../release-bundle.zip .
      - name: Upload zip to triggering release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" release-bundle.zip --clobber
